import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";

const deployAPICredits: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // Deploy PoseidonT3 (required by LeanIMT)
  const poseidon3 = await deploy("PoseidonT3", {
    from: deployer,
    log: true,
    autoMine: true,
  });

  // Deploy LeanIMT library
  const leanIMT = await deploy("LeanIMT", {
    from: deployer,
    log: true,
    autoMine: true,
    libraries: {
      PoseidonT3: poseidon3.address,
    },
  });

  // Deploy the UltraHonk Verifier (generated by bb)
  const verifier = await deploy("HonkVerifier", {
    from: deployer,
    log: true,
    autoMine: true,
  });

  // Deploy APICredits contract
  await deploy("APICredits", {
    from: deployer,
    args: [deployer, verifier.address],
    log: true,
    autoMine: true,
    libraries: {
      LeanIMT: leanIMT.address,
    },
  });
};

export default deployAPICredits;
deployAPICredits.tags = ["APICredits"];
