import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";

const deployAPICredits: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  // Determine CLAWD token address based on network
  let clawdAddress: string;

  if (hre.network.name === "base") {
    // Base mainnet — real CLAWD token
    clawdAddress = "0x9f86dB9fc6f7c9408e8Fda3Ff8ce4e78ac7a6b07";
  } else {
    // Testnet / local — deploy MockERC20
    const mockClawd = await deploy("MockERC20", {
      from: deployer,
      log: true,
      autoMine: true,
    });
    clawdAddress = mockClawd.address;
  }

  // Deploy Poseidon2LeanIMT library (uses Noir-compatible Poseidon2 hash)
  const poseidon2LeanIMT = await deploy("Poseidon2LeanIMT", {
    from: deployer,
    log: true,
    autoMine: true,
  });

  // Deploy the UltraVerifier (generated by bb)
  const verifier = await deploy("UltraVerifier", {
    from: deployer,
    log: true,
    autoMine: true,
  });

  // Deploy APICredits contract
  await deploy("APICredits", {
    from: deployer,
    args: [clawdAddress, deployer, verifier.address],
    log: true,
    autoMine: true,
    libraries: {
      Poseidon2LeanIMT: poseidon2LeanIMT.address,
    },
  });
};

export default deployAPICredits;
deployAPICredits.tags = ["APICredits"];
