import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import os from "os";
import { fileURLToPath } from "url";
import { createPublicClient, http, webSocket, parseAbi, parseAbiItem } from "viem";
import { base } from "viem/chains";
import { Barretenberg, Fr } from "@aztec/bb.js";
import { VerifierPool } from "./verifier-pool.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Initialize Barretenberg for Poseidon2 hashing ────────────
// bb.js poseidon2Hash is the ONLY correct Poseidon2 implementation
// that matches Noir's Poseidon2::hash and the on-chain LibPoseidon2.
// DO NOT use poseidon-lite — its "poseidon2" is original Poseidon with 2 inputs,
// which is a completely different hash function.
let bb: Barretenberg;

async function poseidon2Hash(left: bigint, right: bigint): Promise<bigint> {
  const result = await bb.poseidon2Hash([new Fr(left), new Fr(right)]);
  return BigInt(result.toString());
}

// ─── Precomputed zero hashes (computed at startup) ────────────
const MAX_DEPTH = 16;
let zeros: bigint[] = [];

async function precomputeZeros() {
  zeros = new Array(MAX_DEPTH);
  zeros[0] = 0n;
  for (let i = 0; i < MAX_DEPTH - 1; i++) {
    zeros[i + 1] = await poseidon2Hash(zeros[i], zeros[i]);
  }
  console.log("Zero hashes precomputed.");
}

// ─── Configuration ────────────────────────────────────────────
const PORT = process.env.PORT || 3001;
const VENICE_API_KEY = process.env.VENICE_API_KEY as string;
if (!VENICE_API_KEY) throw new Error("VENICE_API_KEY is required — set it in packages/api-server/.env");
const VENICE_BASE_URL =
  process.env.VENICE_BASE_URL || "https://api.venice.ai/api/v1";
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS as `0x${string}`;
const RPC_URL = process.env.RPC_URL || "https://mainnet.base.org";
const WS_URL = process.env.WS_URL || "";
const NULLIFIER_FILE = process.env.NULLIFIER_FILE || "./data/spent-nullifiers.json";

// Path to the circuit verification key (generated by bb)
const VK_PATH = process.env.VK_PATH || path.resolve(
  __dirname,
  "../../circuits/target/vk"
);

const CIRCUIT_PATH = process.env.CIRCUIT_PATH || path.resolve(__dirname, "../../circuits/target/circuits.json");

// Worker pool for proof verification (initialized in start())
let verifierPool: VerifierPool;

// ─── On-Chain Root Verification ───────────────────────────────
const publicClient = createPublicClient({
  chain: base,
  transport: http(RPC_URL),
});

// WebSocket client for real-time event watching (if WS_URL configured)
const wsClient = WS_URL
  ? createPublicClient({ chain: base, transport: webSocket(WS_URL) })
  : null;

const API_CREDITS_ABI = parseAbi([
  "function getTreeData() view returns (uint256 size, uint256 depth, uint256 root)",
]);

// ─── Historical Root Tracking (Privacy Fix) ───────────────────
// PROBLEM: Accepting only the current onchain root creates a timing
// correlation attack. When a new commitment is registered, the root
// changes. Any proof generated against the old root is rejected,
// forcing users to regenerate proofs immediately — which reveals
// who they are in a low-traffic system.
//
// FIX: Maintain a rolling set of all historical Merkle roots.
// Accept any proof against a root that existed within the last
// VALID_ROOT_WINDOW blocks (~24h on Base). We replay all
// CreditRegistered events on startup to build the full history,
// then poll for new events to keep it updated.

const VALID_ROOT_WINDOW = 7200n; // ~24h on Base (2s block time)

// root hex string → block number when it became the active root
const validRoots = new Map<string, bigint>();

// Persistent Semaphore-style tree state for incremental root computation.
// This mirrors the contract's filledNodes array exactly.
const treeFilledNodes: bigint[] = new Array(MAX_DEPTH).fill(0n);
let treeSize = 0;

// Cached tree leaves for /tree endpoint (avoids RPC calls per request)
const treeLeaves: bigint[] = [];

// The latest (current) root — never pruned from the valid set
let currentRoot: string | null = null;

// Last block processed by the event watcher
let lastProcessedBlock = 0n;

function rootToHex(root: bigint): string {
  return "0x" + root.toString(16).padStart(64, "0");
}

/**
 * Compute the Merkle root from the current filledNodes state.
 * Replicates the contract's _computeRoot logic exactly.
 */
async function computeRootFromFilledNodes(size: number): Promise<bigint> {
  if (size === 0) return 0n;

  let node = 0n;
  let nodeLevel = -1;
  let hasNode = false;

  for (let i = 0; i < MAX_DEPTH; i++) {
    if (((size >> i) & 1) === 1) {
      if (!hasNode) {
        node = treeFilledNodes[i];
        nodeLevel = i;
        hasNode = true;
      } else {
        for (let lvl = nodeLevel; lvl < i; lvl++) {
          node = await poseidon2Hash(node, zeros[lvl]);
        }
        node = await poseidon2Hash(treeFilledNodes[i], node);
        nodeLevel = i + 1;
      }
    }
  }

  return node;
}

/**
 * Insert a leaf into the incremental tree and return the new root.
 * Replicates the contract's Semaphore-style _insert + _computeRoot.
 */
async function insertLeafAndGetRoot(commitment: bigint): Promise<bigint> {
  treeLeaves.push(commitment);
  let node = commitment;
  for (let i = 0; i < MAX_DEPTH; i++) {
    if (((treeSize >> i) & 1) === 0) {
      treeFilledNodes[i] = node;
      break;
    } else {
      node = await poseidon2Hash(treeFilledNodes[i], node);
    }
  }
  treeSize++;
  return computeRootFromFilledNodes(treeSize);
}

/**
 * Prune roots older than VALID_ROOT_WINDOW blocks.
 * The current root is never pruned.
 */
async function pruneOldRoots(): Promise<void> {
  try {
    const currentBlock = await publicClient.getBlockNumber();
    const cutoff = currentBlock > VALID_ROOT_WINDOW
      ? currentBlock - VALID_ROOT_WINDOW
      : 0n;
    let pruned = 0;

    for (const [root, blockNum] of validRoots) {
      if (blockNum < cutoff && root !== currentRoot) {
        validRoots.delete(root);
        pruned++;
      }
    }

    if (pruned > 0) {
      console.log(
        `Pruned ${pruned} roots older than block ${cutoff}. ${validRoots.size} remain.`
      );
    }
  } catch (err) {
    console.error("Error pruning old roots:", err);
  }
}

/**
 * Replay all CreditRegistered events to build the full set of historical roots.
 * Each insertion produces a new root; we store every root with its block number.
 */
async function buildHistoricalRoots(): Promise<void> {
  console.log("Building historical root set from CreditRegistered events...");

  const events = await publicClient.getLogs({
    address: CONTRACT_ADDRESS,
    event: parseAbiItem(
      "event CreditRegistered(address indexed user, uint256 indexed index, uint256 commitment, uint256 newStakedBalance)"
    ),
    fromBlock: 0n,
  });

  if (events.length === 0) {
    console.log("No CreditRegistered events found.");
    return;
  }

  // Sort by index to replay insertions in correct order
  const sorted = events.sort(
    (a, b) => Number(a.args.index!) - Number(b.args.index!)
  );

  for (const event of sorted) {
    const root = await insertLeafAndGetRoot(event.args.commitment!);
    const rootHex = rootToHex(root);
    validRoots.set(rootHex, event.blockNumber);
    currentRoot = rootHex;

    // Also register the compact root for this tree state
    const compactRoot = await computeCompactRoot(treeLeaves);
    if (compactRoot !== null) {
      const compactRootHex = rootToHex(compactRoot);
      if (compactRootHex !== rootHex) {
        validRoots.set(compactRootHex, event.blockNumber);
      }
    }
  }

  // Verify our computed root matches the contract's current root
  try {
    const [, , contractRoot] = await publicClient.readContract({
      address: CONTRACT_ADDRESS,
      abi: API_CREDITS_ABI,
      functionName: "getTreeData",
    });
    const contractRootHex = rootToHex(contractRoot);
    if (currentRoot === contractRootHex) {
      console.log(`✓ Computed root matches onchain: ${currentRoot}`);
    } else {
      console.error(
        `✗ ROOT MISMATCH! Computed: ${currentRoot}, Onchain: ${contractRootHex}`
      );
    }
  } catch {
    console.log("Could not verify root against contract (may be empty).");
  }

  console.log(
    `Built ${validRoots.size} historical roots from ${events.length} events.`
  );

  // Prune roots outside the validity window
  await pruneOldRoots();
}

/**
 * Poll for new CreditRegistered events every 10 seconds.
 * Updates the tree state and valid roots set incrementally.
 */
/**
 * Compute the compact Merkle root from a list of leaves.
 * depth = ceil(log2(n)), padded with zeros[0] on right.
 * This is the root clients generate proofs against via /tree.
 */
async function computeCompactRoot(leaves: bigint[]): Promise<bigint | null> {
  const n = leaves.length;
  if (n === 0) return null;

  let depth = 0;
  let tmp = n;
  while (tmp > 1) { depth++; tmp = Math.ceil(tmp / 2); }

  const level0Size = depth === 0 ? 1 : 1 << depth;
  let level: bigint[] = new Array(level0Size);
  for (let i = 0; i < level0Size; i++) {
    level[i] = i < n ? leaves[i] : zeros[0];
  }
  for (let lvl = 0; lvl < depth; lvl++) {
    const parentSize = level.length >> 1;
    const parent: bigint[] = new Array(parentSize);
    for (let j = 0; j < parentSize; j++) {
      parent[j] = await poseidon2Hash(level[j * 2], level[j * 2 + 1]);
    }
    level = parent;
  }
  return level[0];
}

async function handleNewEvent(event: {
  args: { commitment?: bigint; index?: bigint };
  blockNumber: bigint | null;
}): Promise<void> {
  if (!event.args.commitment || event.blockNumber === null) return;
  const root = await insertLeafAndGetRoot(event.args.commitment);
  const rootHex = rootToHex(root);
  validRoots.set(rootHex, event.blockNumber);
  currentRoot = rootHex;
  if (event.blockNumber > lastProcessedBlock) lastProcessedBlock = event.blockNumber;

  // Also register the compact root that /tree returns — clients generate
  // proofs against this root (depth=ceil(log2(n))), not the incremental root.
  const compactRoot = await computeCompactRoot(treeLeaves);
  if (compactRoot !== null) {
    const compactRootHex = rootToHex(compactRoot);
    if (compactRootHex !== rootHex) {
      validRoots.set(compactRootHex, event.blockNumber);
    }
  }

  console.log(`New root: ${rootHex} (block ${event.blockNumber}, index ${event.args.index})`);
  await pruneOldRoots();
}

function startEventWatcher(): void {
  const eventAbi = parseAbiItem(
    "event CreditRegistered(address indexed user, uint256 indexed index, uint256 commitment, uint256 newStakedBalance)"
  );

  if (wsClient) {
    // ── WebSocket path: fires within ~1 block (~2s) of tx confirmation ──
    wsClient.watchContractEvent({
      address: CONTRACT_ADDRESS,
      abi: [eventAbi],
      eventName: "CreditRegistered",
      onLogs: async (logs) => {
        const sorted = [...logs].sort((a, b) => Number(a.args.index!) - Number(b.args.index!));
        for (const log of sorted) {
          await handleNewEvent(log).catch(err =>
            console.error("Event handler error:", err)
          );
        }
      },
      onError: (err) => console.error("WebSocket watcher error:", err),
    });
    console.log("Event watcher started (WebSocket — real-time).");
  }

  // ── Polling fallback: runs every 2s regardless (catches WS gaps) ──
  setInterval(async () => {
    try {
      const currentBlock = await publicClient.getBlockNumber();
      if (currentBlock <= lastProcessedBlock) return;

      const events = await publicClient.getLogs({
        address: CONTRACT_ADDRESS,
        event: eventAbi,
        fromBlock: lastProcessedBlock + 1n,
        toBlock: currentBlock,
      });

      if (events.length > 0) {
        const sorted = events.sort((a, b) => Number(a.args.index!) - Number(b.args.index!));
        for (const event of sorted) {
          await handleNewEvent(event).catch(err =>
            console.error("Poll handler error:", err)
          );
        }
      } else {
        lastProcessedBlock = currentBlock;
      }
    } catch (err) {
      console.error("Poll watcher error:", err);
    }
  }, 2_000);

  if (!wsClient) console.log("Event watcher started (polling every 2s — set WS_URL for real-time).");
}

// ─── Nullifier Persistence ────────────────────────────────────
function loadNullifiers(): Set<string> {
  try {
    fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
    const data = JSON.parse(fs.readFileSync(NULLIFIER_FILE, "utf-8"));
    return new Set(data);
  } catch {
    return new Set();
  }
}

function saveNullifier(hash: string) {
  spentNullifiers.add(hash);
  fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
  fs.writeFileSync(NULLIFIER_FILE, JSON.stringify([...spentNullifiers]));
}

const spentNullifiers = loadNullifiers();
const pendingNullifiers = new Set<string>();

// ─── Model (locked for demo — one credit, one model) ─────────
const MODEL = process.env.VENICE_MODEL || "hermes-3-llama-3.1-405b";

// ─── Express App ──────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// Health check
app.get("/health", async (_req, res) => {
  res.json({
    status: "ok",
    spentNullifiers: spentNullifiers.size,
    currentRoot,
    validRoots: validRoots.size,
    treeSize,
  });
});

// Get server stats
app.get("/stats", async (_req, res) => {
  res.json({
    spentNullifiers: spentNullifiers.size,
    currentRoot,
    validRoots: validRoots.size,
    treeSize,
  });
});

// Check if a nullifier has been spent
app.get("/nullifier/:hash", (req, res) => {
  const spent = spentNullifiers.has(req.params.hash);
  res.json({ spent });
});

// ─── Contract Info ─────────────────────────────────────────────
// GET /contract — returns current contract address (for update.sh auto-sync)
app.get("/contract", (_req, res) => {
  res.json({ address: CONTRACT_ADDRESS, chainId: 8453 });
});

// ─── Circuit Artifact ──────────────────────────────────────────
// GET /circuit
// Returns the compiled Noir circuit JSON for client-side proof generation
app.get("/circuit", (_req, res) => {
  try {
    const circuitPath = process.env.CIRCUIT_PATH || path.resolve(__dirname, "../../circuits/target/circuits.json");
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.json(circuit);
  } catch (err: any) {
    res.status(500).json({ error: "Circuit not found: " + err.message });
  }
});

// ─── Full Tree Data (Privacy-Preserving) ──────────────────────
// GET /tree
// Returns ALL tree data (leaves, precomputed levels, root, depth, zeros).
// The client computes its own Merkle path locally — the server never learns
// which commitment is about to be used. This replaces /merkle-path/:commitment.
app.get("/tree", async (_req, res) => {
  const tTree = Date.now();
  try {
    const leaves = treeLeaves;
    const numLeaves = leaves.length;

    if (numLeaves === 0) {
      res.json({
        leaves: [],
        levels: [],
        root: "0",
        depth: 0,
        zeros: zeros.map((z) => z.toString()),
      });
      return;
    }

    // Use the actual tree depth (ceil(log2(numLeaves))) for Merkle paths.
    // The circuit uses MAX_DEPTH=16 — clients pad indices/siblings to 16.
    // The root must match the incremental Semaphore-style tree, so we
    // compute depth levels for path extraction, then fold remaining
    // levels up to MAX_DEPTH using zero hashes (same as the contract).
    let treeDepth = 0;
    {
      let tmp = numLeaves;
      while (tmp > 1) {
        treeDepth++;
        tmp = Math.ceil(tmp / 2);
      }
    }

    // Build full level-by-level tree from cached leaves (no RPC calls)
    const levels: bigint[][] = [];
    const level0Size = treeDepth === 0 ? 1 : 1 << treeDepth;
    levels[0] = new Array(level0Size);
    for (let i = 0; i < level0Size; i++) {
      levels[0][i] = i < numLeaves ? leaves[i] : zeros[0];
    }
    for (let lvl = 0; lvl < treeDepth; lvl++) {
      const parentSize = levels[lvl].length >> 1;
      levels[lvl + 1] = new Array(parentSize);
      for (let j = 0; j < parentSize; j++) {
        levels[lvl + 1][j] = await poseidon2Hash(levels[lvl][j * 2], levels[lvl][j * 2 + 1]);
      }
    }

    const treeRoot = levels[treeDepth]?.[0] ?? leaves[0];

    console.log(`[tree] built ${numLeaves} leaves (depth ${treeDepth}) in ${Date.now() - tTree}ms`);
    res.json({
      leaves: leaves.map((l) => l.toString()),
      levels: levels.map((level) => level.map((n) => n.toString())),
      root: treeRoot.toString(),
      depth: treeDepth,
      zeros: zeros.map((z) => z.toString()),
    });
  } catch (err: any) {
    console.error(`[tree] error after ${Date.now() - tTree}ms:`, err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * Main API endpoint — verify proof + proxy to Venice
 *
 * POST /v1/chat
 * {
 *   "proof": "<hex string>",
 *   "nullifier_hash": "0x...",
 *   "root": "0x...",
 *   "depth": 16,
 *   "messages": [{ "role": "user", "content": "..." }],
 * }
 */
app.post("/v1/chat", async (req, res) => {
  const reqId = Math.random().toString(36).slice(2, 8);
  const t0 = Date.now();
  const ts = () => `+${Date.now() - t0}ms`;
  console.log(`[${reqId}] POST /v1/chat — received`);

  const {
    proof,
    nullifier_hash,
    root,
    depth,
    messages,
    encrypted_messages,
  } = req.body;

  if (req.body.model && req.body.model !== MODEL) {
    console.log(`[${reqId}] client requested model "${req.body.model}" — ignored, using "${MODEL}"`);
  }

  // E2EE mode: encrypted_messages replaces messages
  const isE2EE = !!encrypted_messages;

  // ─── Input Validation ───────────────────────────────────
  if (!proof || !nullifier_hash || !root || depth === undefined) {
    res.status(400).json({
      error: "Missing required fields: proof, nullifier_hash, root, depth",
    });
    return;
  }
  if (!isE2EE && (!messages || !Array.isArray(messages))) {
    res.status(400).json({
      error: "Missing required field: messages (or encrypted_messages for E2EE)",
    });
    return;
  }

  // ─── Double-spend protection (synchronous, before any await) ──
  if (spentNullifiers.has(nullifier_hash)) {
    console.log(`[${reqId}] nullifier already spent (${ts()})`);
    res.status(403).json({ error: "Nullifier already spent" });
    return;
  }
  if (pendingNullifiers.has(nullifier_hash)) {
    console.log(`[${reqId}] nullifier already pending (${ts()})`);
    res.status(429).json({ error: "This nullifier is currently being processed — try again in a moment" });
    return;
  }
  pendingNullifiers.add(nullifier_hash);
  console.log(`[${reqId}] nullifier + root checks passed (${ts()})`);

  try {
    // ─── Verify root is in the valid historical set ─────────
    console.log(`[${reqId}] root check: validRoots.size=${validRoots.size}, checking root=${root.slice(0, 20)}... (${ts()})`);
    if (validRoots.size === 0) {
      console.log(`[${reqId}] no valid roots (${ts()})`);
      res.status(403).json({ error: "No commitments registered yet" });
      return;
    }
    if (!validRoots.has(root)) {
      console.log(`[${reqId}] root not in valid set (${ts()})`);
      res.status(403).json({
        error: "Invalid root — not in valid root set (may be expired or incorrect)",
      });
      return;
    }
    console.log(`[${reqId}] root valid ✅ (${ts()})`);

    // ─── Verify ZK proof ───────────────────────────────────
    const tVerifyStart = Date.now();
    console.log(`[${reqId}] starting proof verification (${ts()})`);
    try {
      const proofValid = await verifyProof(proof, nullifier_hash, root, depth);
      const verifyMs = Date.now() - tVerifyStart;
      if (!proofValid) {
        console.log(`[${reqId}] proof INVALID — ${verifyMs}ms`);
        res.status(403).json({ error: "Invalid proof" });
        return;
      }
      console.log(`[${reqId}] proof verified ✅ — ${verifyMs}ms`);
    } catch (verifyError: any) {
      const verifyMs = Date.now() - tVerifyStart;
      console.error(`[${reqId}] proof verification threw — ${verifyMs}ms:`, verifyError);
      res.status(403).json({
        error: "Proof verification failed",
        details: verifyError.message,
      });
      return;
    }

    // ─── Mark nullifier as spent BEFORE Venice call ─────────
    saveNullifier(nullifier_hash);
    console.log(`[${reqId}] nullifier burned (${ts()})`);

    // ─── Forward to Venice API ──────────────────────────────
    const tVeniceStart = Date.now();
    console.log(`[${reqId}] calling Venice (${ts()})${isE2EE ? " [E2EE 🔒 — forwarding blind]" : ""}`);
    try {
      // Pass E2EE headers from client through to Venice if present
      const veniceHeaders: Record<string, string> = {
        "Content-Type": "application/json",
        Authorization: `Bearer ${VENICE_API_KEY}`,
      };
      const e2eeHeaderNames = [
        "x-venice-tee-client-pub-key",
        "x-venice-tee-model-pub-key",
        "x-venice-tee-signing-algo",
      ];
      for (const h of e2eeHeaderNames) {
        const val = req.headers[h] as string | undefined;
        if (val) veniceHeaders[h] = val;
      }

      // Build Venice request body
      // NOTE: always stream: false — server does veniceResponse.json(), not SSE piping
      const veniceBody: Record<string, any> = {
        model: MODEL,
        stream: false,
      };
      if (isE2EE) {
        // E2EE: forward encrypted blob, Venice TEE will decrypt
        veniceBody.encrypted_messages = encrypted_messages;
        veniceBody.messages = []; // required field, sent empty
      } else {
        veniceBody.messages = messages;
      }

      const veniceResponse = await fetch(
        `${VENICE_BASE_URL}/chat/completions`,
        {
          method: "POST",
          headers: veniceHeaders,
          body: JSON.stringify(veniceBody),
        }
      );

      const veniceMs = Date.now() - tVeniceStart;

      if (!veniceResponse.ok) {
        const errorText = await veniceResponse.text();
        console.error(`[${reqId}] Venice error ${veniceResponse.status} — ${veniceMs}ms:`, errorText);
        res.status(502).json({
          error: "Venice API error",
          status: veniceResponse.status,
        });
        return;
      }

      const veniceData = await veniceResponse.json();
      const totalMs = Date.now() - t0;
      console.log(`[${reqId}] ✅ done — Venice: ${veniceMs}ms | total: ${totalMs}ms`);
      res.json(veniceData);
    } catch (veniceError: any) {
      const veniceMs = Date.now() - tVeniceStart;
      console.error(`[${reqId}] Venice request failed — ${veniceMs}ms:`, veniceError);
      res.status(502).json({
        error: "Failed to reach Venice API",
        details: veniceError.message,
      });
      return;
    }
  } catch (error: any) {
    console.error(`[${reqId}] unexpected error (${ts()}):`, error);
    res.status(500).json({ error: "Internal server error" });
  } finally {
    pendingNullifiers.delete(nullifier_hash);
  }
});

// ─── Proof Verification ───────────────────────────────────────
async function verifyProof(
  proofHex: string,
  nullifierHash: string,
  root: string,
  depth: number,
): Promise<boolean> {
  try {
    const publicInputs = [
      nullifierHash,
      root,
      "0x" + BigInt(depth).toString(16).padStart(64, "0"),
    ];
    return await verifierPool.verify(proofHex, publicInputs);
  } catch (error) {
    console.error("Proof verification error:", error);
    return false;
  }
}

// ─── Start Server ─────────────────────────────────────────────
async function start() {
  console.log("Initializing Barretenberg (Poseidon2 WASM)...");
  bb = await Barretenberg.new({ threads: 1 });
  console.log("Barretenberg ready.");

  // Precompute zero hashes (must happen after bb is initialized)
  await precomputeZeros();

  // Build historical root set from all past events
  await buildHistoricalRoots();

  // Initialize verifier worker pool
  const poolSize = Math.max(1, os.cpus().length - 1);
  console.log(`Initializing verifier pool (${poolSize} workers)...`);
  const workerScript = path.resolve(__dirname, "verifier-worker.js");
  const circuit = JSON.parse(fs.readFileSync(CIRCUIT_PATH, "utf-8"));
  verifierPool = new VerifierPool(circuit.bytecode, workerScript, poolSize);
  await verifierPool.init();
  console.log(`Verifier pool ready (${poolSize} workers, WASM hot)`);

  // Record current block for incremental watching
  try {
    lastProcessedBlock = await publicClient.getBlockNumber();
  } catch {
    lastProcessedBlock = 0n;
  }

  // Start polling for new commitment events
  startEventWatcher();

  app.listen(PORT, () => {
    console.log(`\n🔐 ZK API Credits Server`);
    console.log(`   Port: ${PORT}`);
    console.log(`   Model: ${MODEL}`);
    console.log(`   Venice: ${VENICE_BASE_URL}`);
    console.log(`   VK: ${VK_PATH}`);
    console.log(`   Contract: ${CONTRACT_ADDRESS}`);
    console.log(`   RPC: ${RPC_URL}`);
    console.log(`   WS:  ${WS_URL || "(not set — WebSocket disabled, using 2s polling)"}`);
    console.log(`   Current root: ${currentRoot || "(no commitments yet)"}`);
    console.log(`   Valid roots: ${validRoots.size} (window: ${VALID_ROOT_WINDOW} blocks)`);
    console.log(`   Tree size: ${treeSize} commitments`);
    console.log(`   Loaded nullifiers: ${spentNullifiers.size}`);
    console.log(`   Nullifier file: ${NULLIFIER_FILE}`);
    console.log(`   Hash function: bb.js Poseidon2 (Noir-compatible)`);
    console.log(`   Tree type: Standard binary with zero-padding (Semaphore-style)`);
    console.log(`   Verifier pool: ${verifierPool.size} workers (UltraHonkBackend pre-warmed)`);
    console.log(`\n   POST /v1/chat — Submit proof + get LLM response`);
    console.log(`   GET  /health  — Server health + valid roots count`);
    console.log(`   GET  /stats   — Server stats`);
    console.log(`\n   No wallet. No API key. No identity.\n`);
  });
}

start().catch(console.error);
