import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createPublicClient, http, parseAbi, parseAbiItem } from "viem";
import { base } from "viem/chains";
import { Barretenberg, Fr } from "@aztec/bb.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Initialize Barretenberg for Poseidon2 hashing ────────────
// bb.js poseidon2Hash is the ONLY correct Poseidon2 implementation
// that matches Noir's Poseidon2::hash and the on-chain LibPoseidon2.
// DO NOT use poseidon-lite — its "poseidon2" is original Poseidon with 2 inputs,
// which is a completely different hash function.
let bb: Barretenberg;

async function poseidon2Hash(left: bigint, right: bigint): Promise<bigint> {
  const result = await bb.poseidon2Hash([new Fr(left), new Fr(right)]);
  return BigInt(result.toString());
}

// ─── Precomputed zero hashes (computed at startup) ────────────
const MAX_DEPTH = 16;
let zeros: bigint[] = [];

async function precomputeZeros() {
  zeros = new Array(MAX_DEPTH);
  zeros[0] = 0n;
  for (let i = 0; i < MAX_DEPTH - 1; i++) {
    zeros[i + 1] = await poseidon2Hash(zeros[i], zeros[i]);
  }
  console.log("Zero hashes precomputed.");
}

// ─── Configuration ────────────────────────────────────────────
const PORT = process.env.PORT || 3001;
const VENICE_API_KEY =
  process.env.VENICE_API_KEY ||
  "VENICE_INFERENCE_KEY_KGq6jatZVf4-daQeEzsDwilsVcnef8T0mC77mu7d3B";
const VENICE_BASE_URL =
  process.env.VENICE_BASE_URL || "https://api.venice.ai/api/v1";
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS as `0x${string}`;
const RPC_URL = process.env.RPC_URL || "https://mainnet.base.org";
const NULLIFIER_FILE = process.env.NULLIFIER_FILE || "./data/spent-nullifiers.json";

// Path to the circuit verification key (generated by bb)
const VK_PATH = process.env.VK_PATH || path.resolve(
  __dirname,
  "../../circuits/target/vk"
);

// ─── On-Chain Root Verification ───────────────────────────────
const publicClient = createPublicClient({
  chain: base,
  transport: http(RPC_URL),
});

const API_CREDITS_ABI = parseAbi([
  "function getTreeData() view returns (uint256 size, uint256 depth, uint256 root)",
]);

let cachedRoot: string | null = null;
let cachedRootTimestamp = 0;
const ROOT_CACHE_TTL_MS = 5000; // 5 seconds

async function getOnChainRoot(): Promise<string | null> {
  const now = Date.now();
  if (cachedRoot !== null && now - cachedRootTimestamp < ROOT_CACHE_TTL_MS) {
    return cachedRoot;
  }
  try {
    const [, , root] = await publicClient.readContract({
      address: CONTRACT_ADDRESS,
      abi: API_CREDITS_ABI,
      functionName: "getTreeData",
    });
    cachedRoot = "0x" + root.toString(16).padStart(64, "0");
    cachedRootTimestamp = now;
    return cachedRoot;
  } catch {
    // Tree is empty or contract not deployed
    cachedRoot = null;
    cachedRootTimestamp = now;
    return null;
  }
}

// ─── Nullifier Persistence ────────────────────────────────────
function loadNullifiers(): Set<string> {
  try {
    fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
    const data = JSON.parse(fs.readFileSync(NULLIFIER_FILE, "utf-8"));
    return new Set(data);
  } catch {
    return new Set();
  }
}

function saveNullifier(hash: string) {
  spentNullifiers.add(hash);
  fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
  fs.writeFileSync(NULLIFIER_FILE, JSON.stringify([...spentNullifiers]));
}

const spentNullifiers = loadNullifiers();

// ─── Express App ──────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// Health check
app.get("/health", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    status: "ok",
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Get server stats
app.get("/stats", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Check if a nullifier has been spent
app.get("/nullifier/:hash", (req, res) => {
  const spent = spentNullifiers.has(req.params.hash);
  res.json({ spent });
});

// ─── Circuit Artifact ──────────────────────────────────────────
// GET /circuit
// Returns the compiled Noir circuit JSON for client-side proof generation
app.get("/circuit", (_req, res) => {
  try {
    const circuitPath = process.env.CIRCUIT_PATH || path.resolve(__dirname, "../../circuits/target/circuits.json");
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.json(circuit);
  } catch (err: any) {
    res.status(500).json({ error: "Circuit not found: " + err.message });
  }
});

// ─── Merkle Path for ZK Proof Generation ──────────────────────
// GET /merkle-path/:commitment
// Returns the Merkle sibling path for a given commitment (leaf value).
// Frontend needs this to generate ZK proofs.
//
// IMPORTANT: This builds a STANDARD BINARY Merkle tree with zero-padding.
// Empty positions use precomputed zeros (zeros[level]).
// This matches the Noir circuit's binary_merkle_root EXACTLY.
// NO LeanIMT promotion — every level hashes two children.
app.get("/merkle-path/:commitment", async (req, res) => {
  try {
    // Read all CreditRegistered events from the contract to reconstruct the tree
    const events = await publicClient.getLogs({
      address: CONTRACT_ADDRESS,
      event: parseAbiItem(
        "event CreditRegistered(address indexed user, uint256 indexed index, uint256 commitment, uint256 newStakedBalance)"
      ),
      fromBlock: 0n,
    });

    if (events.length === 0) {
      res.status(404).json({ error: "No commitments registered yet" });
      return;
    }

    // Sort by index and extract commitment values
    const leaves: bigint[] = events
      .sort((a, b) => Number(a.args.index!) - Number(b.args.index!))
      .map((e) => e.args.commitment!);

    const targetCommitment = BigInt(req.params.commitment);
    const leafIndex = leaves.findIndex((l) => l === targetCommitment);

    if (leafIndex === -1) {
      res.status(404).json({ error: "Commitment not found in tree" });
      return;
    }

    const numLeaves = leaves.length;

    // Compute tree depth — matches contract exactly:
    // 1 leaf → depth 0 (root IS the leaf, no hashing)
    // 2 leaves → depth 1, 3-4 → depth 2, 5-8 → depth 3, etc.
    let treeDepth = 0;
    {
      let tmp = numLeaves;
      while (tmp > 1) {
        treeDepth++;
        tmp = Math.ceil(tmp / 2);
      }
    }

    // Build the full binary tree level by level using incremental filledNodes logic
    // to match _computeRoot in the contract exactly.
    //
    // We simulate the Semaphore-style insert for all leaves to get filledNodes,
    // then compute the root the same way _computeRoot does.
    const filledNodes: bigint[] = new Array(MAX_DEPTH).fill(0n);
    for (let li = 0; li < numLeaves; li++) {
      let node = leaves[li];
      for (let i = 0; i < MAX_DEPTH; i++) {
        if (((li >> i) & 1) === 0) {
          filledNodes[i] = node;
          break;
        } else {
          node = await poseidon2Hash(filledNodes[i], node);
        }
      }
    }

    // _computeRoot logic
    let treeRoot: bigint;
    {
      let node = 0n;
      let nodeLevel = -1;
      let hasNode = false;
      for (let i = 0; i < MAX_DEPTH; i++) {
        if (((numLeaves >> i) & 1) === 1) {
          if (!hasNode) {
            node = filledNodes[i];
            nodeLevel = i;
            hasNode = true;
          } else {
            for (let lvl = nodeLevel; lvl < i; lvl++) {
              node = await poseidon2Hash(node, zeros[lvl]);
            }
            node = await poseidon2Hash(filledNodes[i], node);
            nodeLevel = i + 1;
          }
        }
      }
      treeRoot = node;
    }

    // Also build level-by-level tree for sibling extraction
    // Use treeDepth levels, pad right side with zeros[level]
    const levels: bigint[][] = [];
    // Level 0: leaves, right-padded with zeros[0]=0
    const level0Size = treeDepth === 0 ? 1 : (1 << treeDepth);
    levels[0] = new Array(level0Size);
    for (let i = 0; i < level0Size; i++) {
      levels[0][i] = i < numLeaves ? leaves[i] : zeros[0];
    }
    for (let lvl = 0; lvl < treeDepth; lvl++) {
      const parentSize = levels[lvl].length >> 1;
      levels[lvl + 1] = new Array(parentSize);
      for (let j = 0; j < parentSize; j++) {
        levels[lvl + 1][j] = await poseidon2Hash(levels[lvl][j * 2], levels[lvl][j * 2 + 1]);
      }
    }

    // Extract sibling path for the target leaf
    const siblings: string[] = [];
    const indices: number[] = [];
    let currentIndex = leafIndex;

    for (let i = 0; i < MAX_DEPTH; i++) {
      if (i < treeDepth) {
        const siblingIndex = currentIndex ^ 1; // flip last bit
        siblings.push(levels[i][siblingIndex].toString());
      } else {
        siblings.push(zeros[i].toString());
      }
      indices.push((leafIndex >> i) & 1);
      currentIndex = currentIndex >> 1;
    }

    res.json({
      leafIndex,
      siblings,
      indices,
      root: treeRoot.toString(),
      depth: treeDepth,
    });
  } catch (err: any) {
    console.error("Merkle path error:", err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * Main API endpoint — verify proof + proxy to Venice
 *
 * POST /v1/chat
 * {
 *   "proof": "<hex string>",
 *   "nullifier_hash": "0x...",
 *   "root": "0x...",
 *   "depth": 16,
 *   "messages": [{ "role": "user", "content": "..." }],
 *   "model": "llama-3.3-70b"
 * }
 */
app.post("/v1/chat", async (req, res) => {
  try {
    const { proof, nullifier_hash, root, depth, messages, model } = req.body;

    // ─── Input Validation ───────────────────────────────────
    if (!proof || !nullifier_hash || !root || depth === undefined || !messages) {
      res.status(400).json({
        error: "Missing required fields: proof, nullifier_hash, root, depth, messages",
      });
      return;
    }

    // ─── Check nullifier not already spent ──────────────────
    if (spentNullifiers.has(nullifier_hash)) {
      res.status(403).json({ error: "Nullifier already spent" });
      return;
    }

    // ─── Verify root matches on-chain state ─────────────────
    const onChainRoot = await getOnChainRoot();
    if (onChainRoot === null) {
      res.status(403).json({ error: "No commitments registered yet" });
      return;
    }
    if (root !== onChainRoot) {
      res.status(403).json({ error: "Invalid root — does not match on-chain state" });
      return;
    }

    // ─── Verify ZK proof ────────────────────────────────────
    try {
      const proofValid = await verifyProof(proof, nullifier_hash, root, depth);
      if (!proofValid) {
        res.status(403).json({ error: "Invalid proof" });
        return;
      }
    } catch (verifyError: any) {
      console.error("Proof verification error:", verifyError);
      res.status(403).json({
        error: "Proof verification failed",
        details: verifyError.message,
      });
      return;
    }

    // ─── Mark nullifier as spent BEFORE Venice call ─────────
    saveNullifier(nullifier_hash);

    // ─── Forward to Venice API ──────────────────────────────
    try {
      const veniceResponse = await fetch(
        `${VENICE_BASE_URL}/chat/completions`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${VENICE_API_KEY}`,
          },
          body: JSON.stringify({
            model: model || "llama-3.3-70b",
            messages,
            stream: false,
          }),
        }
      );

      if (!veniceResponse.ok) {
        const errorText = await veniceResponse.text();
        console.error("Venice API error:", veniceResponse.status, errorText);
        res.status(502).json({
          error: "Venice API error",
          status: veniceResponse.status,
        });
        return;
      }

      const veniceData = await veniceResponse.json();
      res.json(veniceData);
    } catch (veniceError: any) {
      console.error("Venice request failed:", veniceError);
      res.status(502).json({
        error: "Failed to reach Venice API",
        details: veniceError.message,
      });
      return;
    }
  } catch (error: any) {
    console.error("Unexpected error:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Proof Verification ───────────────────────────────────────
async function verifyProof(
  proofHex: string,
  nullifierHash: string,
  root: string,
  depth: number
): Promise<boolean> {
  try {
    const { UltraHonkBackend } = await import("@aztec/bb.js");

    const vkData = fs.readFileSync(VK_PATH);

    const proofBytes = Buffer.from(
      proofHex.startsWith("0x") ? proofHex.slice(2) : proofHex,
      "hex"
    );

    const publicInputs = [
      nullifierHash,
      root,
      "0x" + BigInt(depth).toString(16).padStart(64, "0"),
    ];

    const circuitPath = process.env.CIRCUIT_PATH || path.resolve(__dirname, "../../circuits/target/circuits.json");
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));

    const backend = new UltraHonkBackend(circuit.bytecode);

    const proof = {
      proof: proofBytes,
      publicInputs: publicInputs,
    };

    const valid = await backend.verifyProof(proof as any);
    return valid;
  } catch (error) {
    console.error("Proof verification error:", error);
    return false;
  }
}

// ─── Start Server ─────────────────────────────────────────────
async function start() {
  console.log("Initializing Barretenberg (Poseidon2 WASM)...");
  bb = await Barretenberg.new({ threads: 1 });
  console.log("Barretenberg ready.");

  // Precompute zero hashes (must happen after bb is initialized)
  await precomputeZeros();

  app.listen(PORT, async () => {
    const onChainRoot = await getOnChainRoot();
    console.log(`\n🔐 ZK API Credits Server`);
    console.log(`   Port: ${PORT}`);
    console.log(`   Venice: ${VENICE_BASE_URL}`);
    console.log(`   VK: ${VK_PATH}`);
    console.log(`   Contract: ${CONTRACT_ADDRESS}`);
    console.log(`   RPC: ${RPC_URL}`);
    console.log(`   On-chain root: ${onChainRoot || "(no commitments yet)"}`);
    console.log(`   Loaded nullifiers: ${spentNullifiers.size}`);
    console.log(`   Nullifier file: ${NULLIFIER_FILE}`);
    console.log(`   Hash function: bb.js Poseidon2 (Noir-compatible)`);
    console.log(`   Tree type: Standard binary with zero-padding (Semaphore-style)`);
    console.log(`\n   POST /v1/chat — Submit proof + get LLM response`);
    console.log(`   GET  /health  — Server health`);
    console.log(`   GET  /stats   — Spent nullifiers count`);
    console.log(`\n   No wallet. No API key. No identity.\n`);
  });
}

start().catch(console.error);
