import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createPublicClient, http, parseAbi } from "viem";
import { base } from "viem/chains";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Configuration ────────────────────────────────────────────
const PORT = process.env.PORT || 3001;
const VENICE_API_KEY =
  process.env.VENICE_API_KEY ||
  "VENICE_INFERENCE_KEY_KGq6jatZVf4-daQeEzsDwilsVcnef8T0mC77mu7d3B";
const VENICE_BASE_URL =
  process.env.VENICE_BASE_URL || "https://api.venice.ai/api/v1";
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS as `0x${string}`;
const RPC_URL = process.env.RPC_URL || "https://mainnet.base.org";
const NULLIFIER_FILE = process.env.NULLIFIER_FILE || "./data/spent-nullifiers.json";

// Path to the circuit verification key (generated by bb)
const VK_PATH = path.resolve(
  __dirname,
  "../../circuits/target/vk"
);

// ─── On-Chain Root Verification ───────────────────────────────
const publicClient = createPublicClient({
  chain: base,
  transport: http(RPC_URL),
});

const API_CREDITS_ABI = parseAbi([
  "function getTreeData() view returns (uint256 size, uint256 depth, uint256 root)",
]);

let cachedRoot: string | null = null;
let cachedRootTimestamp = 0;
const ROOT_CACHE_TTL_MS = 5000; // 5 seconds

async function getOnChainRoot(): Promise<string | null> {
  const now = Date.now();
  if (cachedRoot !== null && now - cachedRootTimestamp < ROOT_CACHE_TTL_MS) {
    return cachedRoot;
  }
  try {
    const [, , root] = await publicClient.readContract({
      address: CONTRACT_ADDRESS,
      abi: API_CREDITS_ABI,
      functionName: "getTreeData",
    });
    cachedRoot = "0x" + root.toString(16).padStart(64, "0");
    cachedRootTimestamp = now;
    return cachedRoot;
  } catch {
    // Tree is empty or contract not deployed
    cachedRoot = null;
    cachedRootTimestamp = now;
    return null;
  }
}

// ─── Nullifier Persistence ────────────────────────────────────
function loadNullifiers(): Set<string> {
  try {
    fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
    const data = JSON.parse(fs.readFileSync(NULLIFIER_FILE, "utf-8"));
    return new Set(data);
  } catch {
    return new Set();
  }
}

function saveNullifier(hash: string) {
  spentNullifiers.add(hash);
  fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
  fs.writeFileSync(NULLIFIER_FILE, JSON.stringify([...spentNullifiers]));
}

const spentNullifiers = loadNullifiers();

// ─── Express App ──────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// Health check
app.get("/health", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    status: "ok",
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Get server stats
app.get("/stats", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Check if a nullifier has been spent
app.get("/nullifier/:hash", (req, res) => {
  const spent = spentNullifiers.has(req.params.hash);
  res.json({ spent });
});

/**
 * Main API endpoint — verify proof + proxy to Venice
 *
 * POST /v1/chat
 * {
 *   "proof": "<hex string>",
 *   "nullifier_hash": "0x...",
 *   "root": "0x...",
 *   "depth": 16,
 *   "messages": [{ "role": "user", "content": "..." }],
 *   "model": "llama-3.3-70b"
 * }
 */
app.post("/v1/chat", async (req, res) => {
  try {
    const { proof, nullifier_hash, root, depth, messages, model } = req.body;

    // ─── Input Validation ───────────────────────────────────
    if (!proof || !nullifier_hash || !root || depth === undefined || !messages) {
      res.status(400).json({
        error: "Missing required fields: proof, nullifier_hash, root, depth, messages",
      });
      return;
    }

    // ─── Check nullifier not already spent ──────────────────
    if (spentNullifiers.has(nullifier_hash)) {
      res.status(403).json({ error: "Nullifier already spent" });
      return;
    }

    // ─── Verify root matches on-chain state ─────────────────
    const onChainRoot = await getOnChainRoot();
    if (onChainRoot === null) {
      res.status(403).json({ error: "No commitments registered yet" });
      return;
    }
    if (root !== onChainRoot) {
      res.status(403).json({ error: "Invalid root — does not match on-chain state" });
      return;
    }

    // ─── Verify ZK proof ────────────────────────────────────
    try {
      const proofValid = await verifyProof(proof, nullifier_hash, root, depth);
      if (!proofValid) {
        res.status(403).json({ error: "Invalid proof" });
        return;
      }
    } catch (verifyError: any) {
      console.error("Proof verification error:", verifyError);
      res.status(403).json({
        error: "Proof verification failed",
        details: verifyError.message,
      });
      return;
    }

    // ─── Mark nullifier as spent BEFORE Venice call ─────────
    // This prevents race conditions — if two requests arrive
    // with the same nullifier simultaneously, only the first
    // one gets through.
    saveNullifier(nullifier_hash);

    // ─── Forward to Venice API ──────────────────────────────
    try {
      const veniceResponse = await fetch(
        `${VENICE_BASE_URL}/chat/completions`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${VENICE_API_KEY}`,
          },
          body: JSON.stringify({
            model: model || "llama-3.3-70b",
            messages,
            stream: false,
          }),
        }
      );

      if (!veniceResponse.ok) {
        const errorText = await veniceResponse.text();
        console.error("Venice API error:", veniceResponse.status, errorText);
        // Don't unspend the nullifier — the credit is burned
        res.status(502).json({
          error: "Venice API error",
          status: veniceResponse.status,
        });
        return;
      }

      const veniceData = await veniceResponse.json();
      res.json(veniceData);
    } catch (veniceError: any) {
      console.error("Venice request failed:", veniceError);
      // Credit is burned even on Venice failure — this is the prepaid model
      res.status(502).json({
        error: "Failed to reach Venice API",
        details: veniceError.message,
      });
      return;
    }
  } catch (error: any) {
    console.error("Unexpected error:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Proof Verification ───────────────────────────────────────
async function verifyProof(
  proofHex: string,
  nullifierHash: string,
  root: string,
  depth: number
): Promise<boolean> {
  try {
    // Dynamic import for bb.js (ESM)
    const { UltraHonkBackend } = await import("@aztec/bb.js");

    // Read the verification key
    const vkData = fs.readFileSync(VK_PATH);

    // Parse proof from hex
    const proofBytes = Buffer.from(
      proofHex.startsWith("0x") ? proofHex.slice(2) : proofHex,
      "hex"
    );

    // Public inputs: nullifier_hash, root, depth
    // These must match the order in the Noir circuit
    const publicInputs = [
      nullifierHash,
      root,
      "0x" + BigInt(depth).toString(16).padStart(64, "0"),
    ];

    // Load circuit artifact for verification
    const circuitPath = path.resolve(
      __dirname,
      "../../circuits/target/circuits.json"
    );
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));

    const backend = new UltraHonkBackend(circuit.bytecode);

    // Reconstruct proof object
    const proof = {
      proof: proofBytes,
      publicInputs: publicInputs,
    };

    const valid = await backend.verifyProof(proof as any);
    return valid;
  } catch (error) {
    console.error("Proof verification error:", error);
    return false;
  }
}

// ─── Start Server ─────────────────────────────────────────────
app.listen(PORT, async () => {
  const onChainRoot = await getOnChainRoot();
  console.log(`\n🔐 ZK API Credits Server`);
  console.log(`   Port: ${PORT}`);
  console.log(`   Venice: ${VENICE_BASE_URL}`);
  console.log(`   VK: ${VK_PATH}`);
  console.log(`   Contract: ${CONTRACT_ADDRESS}`);
  console.log(`   RPC: ${RPC_URL}`);
  console.log(`   On-chain root: ${onChainRoot || "(no commitments yet)"}`);
  console.log(`   Loaded nullifiers: ${spentNullifiers.size}`);
  console.log(`   Nullifier file: ${NULLIFIER_FILE}`);
  console.log(`\n   POST /v1/chat — Submit proof + get LLM response`);
  console.log(`   GET  /health  — Server health`);
  console.log(`   GET  /stats   — Spent nullifiers count`);
  console.log(`\n   No wallet. No API key. No identity.\n`);
});
